version: '3.8'

services:
  currency-converter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iol-challenge
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
